# C:/Valesco_System/engine/modules/pricing_logic_v2.1.py
# Pricing Logic v2.1 — Deterministic Mock Pricing Infrastructure
#
# This module provides foundational, non-hallucinating pricing functions:
#   - Static mock pricing table
#   - Unit-rate lookup
#   - Per-item pricing
#   - Estimate-level pricing using existing Merge Agent snapshots
#
# Constraints:
#   - No inferred quantities
#   - No inferred productivity
#   - No decomposition (materials/plant/labour)
#   - No packs or assemblies
#   - Applies pricing only when quantity is explicitly present
#   - Provisional items remain unpriced (user-supplied only)

from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Static, Deterministic Mock Pricing Table
# ---------------------------------------------------------------------------

MOCK_PRICING: Dict[str, Dict[str, Any]] = {
    "A001": {"unit_rate": 12.50, "unit": "m2"},
    "B001": {"unit_rate": 9.80, "unit": "m"},
    "B002": {"unit_rate": 10.20, "unit": "m"},
    "B003": {"unit_rate": 11.00, "unit": "m"},
    "E001": {"unit_rate": 7.40, "unit": "each"},
    "E002": {"unit_rate": 6.95, "unit": "each"},
}


# ---------------------------------------------------------------------------
# API: Unit Rate Lookup
# ---------------------------------------------------------------------------

def get_unit_rate(item_id: str) -> Optional[Dict[str, Any]]:
    """
    Return the static unit rate and unit for a catalog item.

    Input:
        item_id: catalog item identifier (e.g. "A001")

    Output:
        {
            "unit_rate": float,
            "unit": str,
        }
        or None if the item_id is not priced.
    """
    entry = MOCK_PRICING.get(item_id)
    if entry is None:
        return None
    return {"unit_rate": float(entry["unit_rate"]), "unit": str(entry["unit"])}


# ---------------------------------------------------------------------------
# API: Price a Single Item
# ---------------------------------------------------------------------------

def price_item(item_id: str, quantity: float) -> Optional[Dict[str, Any]]:
    """
    Price a single catalog item for a given quantity.

    Input:
        item_id: catalog item identifier
        quantity: numeric quantity provided by the user or upstream logic

    Output:
        {
            "item_id": item_id,
            "quantity": quantity,
            "unit": <unit>,
            "unit_rate": <unit_rate>,
            "total_cost": quantity * unit_rate,
        }
        or None if item_id has no defined pricing.
    """
    rate_info = get_unit_rate(item_id)
    if rate_info is None:
        return None

    unit_rate = rate_info["unit_rate"]
    unit = rate_info["unit"]
    total_cost = quantity * unit_rate

    return {
        "item_id": item_id,
        "quantity": quantity,
        "unit": unit,
        "unit_rate": unit_rate,
        "total_cost": total_cost,
    }


# ---------------------------------------------------------------------------
# API: Price an Entire Estimate Snapshot
# ---------------------------------------------------------------------------

def price_estimate(estimate_snapshot: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply pricing to an estimate snapshot generated by the Merge Agent.

    Input:
        estimate_snapshot:
            {
                "items": [
                    {
                        "item_id": str | None,
                        "source": "catalog" | "provisional",
                        "display_name": str,
                        "metadata": dict,
                        "status": "confirmed",
                        ... (optional fields such as "quantity", "allowance")
                    },
                    ...
                ]
            }

    Behaviour:
        - For catalog items:
            - If a numeric 'quantity' field is present, apply static pricing.
            - If no quantity, pricing entry indicates "quantity_required".
        - For provisional items:
            - Pricing entry is "user-supplied only".
        - No quantities are inferred.
        - No rates are applied to provisional items.

    Output:
        {
            "items": [
                {
                    "item_id": str | None,
                    "display_name": str,
                    "source": "catalog" | "provisional",
                    "quantity": float | None,
                    "pricing": dict | str | None
                },
                ...
            ]
        }
    """
    items: List[Dict[str, Any]] = estimate_snapshot.get("items", []) or []
    priced_items: List[Dict[str, Any]] = []

    for line in items:
        item_id = line.get("item_id")
        source = line.get("source")
        display_name = line.get("display_name", "")
        quantity = line.get("quantity")

        pricing_entry: Any = None

        if source == "catalog" and item_id is not None:
            rate_info = get_unit_rate(str(item_id))
            if rate_info is None:
                # Catalog item without defined pricing in the mock table.
                pricing_entry = {"pricing": "no_pricing_defined"}
            else:
                if isinstance(quantity, (int, float)):
                    # Apply pricing only when quantity is explicitly provided.
                    priced = price_item(str(item_id), float(quantity))
                    pricing_entry = priced
                else:
                    # Quantity is missing or non-numeric; do not infer.
                    pricing_entry = {"pricing": "quantity_required"}
        else:
            # Provisional or unknown source items are not priced.
            pricing_entry = {"pricing": "user-supplied only"}

        priced_items.append(
            {
                "item_id": item_id,
                "display_name": display_name,
                "source": source,
                "quantity": quantity if isinstance(quantity, (int, float)) else None,
                "pricing": pricing_entry,
            }
        )

    return {"items": priced_items}


# ---------------------------------------------------------------------------
# Minimal Smoke Test (Optional, deterministic)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Example single-item pricing
    print(price_item("A001", 10.0))

    # Example estimate pricing
    sample_estimate = {
        "items": [
            {
                "item_id": "A001",
                "source": "catalog",
                "display_name": "Single Clean-Match Item",
                "metadata": {"id": "A001", "name": "Single Clean-Match Item"},
                "status": "confirmed",
                "quantity": 5.0,
            },
            {
                "item_id": None,
                "source": "provisional",
                "display_name": "Custom non-standard item",
                "metadata": {},
                "status": "confirmed",
            },
        ]
    }
    print(price_estimate(sample_estimate))
